#!/bin/bash

# We have to run--exactly once, on one node--mariadb with
# `--wsrep-new-cluster`. However, this will run *indefinitely*. This wrapper
# script launches that in the background, waits for it to log that it's ready, creates our DB, then kills the node.

LOG="/tmp/galera-bootstrap.log"
READY="ready for connections."
CMD="/usr/sbin/mariadbd --user=root --wsrep-new-cluster --wsrep-cluster-address=gcomm://"

# Launch mariadb in background
$CMD > "$LOG" 2>&1 &
PID=$!

while sleep 1
do
  if fgrep --quiet "$READY" "$LOG"
    then
    echo "Galera bootstrapped"

    # Create DB
    echo "CREATE DATABASE jepsen;
    CREATE USER 'jepsen'@'%' IDENTIFIED BY 'jepsenpw';
    GRANT ALL PRIVILEGES ON jepsen.* TO 'jepsen'@'%';
    FLUSH PRIVILEGES;\n" | /usr/bin/mariadb --user=mysql

    # Kill
    echo "Database created"
    kill -term "$PID"
    exit 0
  fi
done
