#!/bin/bash

# We have to run--exactly once, on one node--mariadb with
# `--wsrep-new-cluster`. However, this will run *indefinitely*. This wrapper
# script launches that in the background, waits for it to log that it's ready,
# then kills it.

LOG="/tmp/galera-bootstrap.log"
READY="ready for connections."
CMD="/usr/sbin/mariadbd --user=root --wsrep-new-cluster --wsrep-cluster-address=gcomm://"

# Launch mariadb in background
$CMD > "$LOG" 2>&1 &
PID=$!

while sleep 1
do
  if fgrep --quiet "$READY" "$LOG"
    then
    echo "Galera bootstrapped"
    kill -term "$PID"
    exit 0
  fi
done
